const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',

    //ADMIN
    FETCH_DATA_GENDER_START: 'FETCH_DATA_GENDER_START',
    FETCH_DATA_GENDER_SUCCESS: 'FETCH_DATA_GENDER_SUCCESS',
    FETCH_DATA_GENDER_FAILED: 'FETCH_DATA_GENDER_FAILED',

    FETCH_DATA_ROLE_SUCCESS: 'FETCH_DATA_ROLE_SUCCESS',
    FETCH_DATA_ROLE_FAILED: 'FETCH_DATA_ROLE_FAILED',

    FETCH_DATA_POSITION_SUCCESS: 'FETCH_DATA_POSITION_SUCCESS',
    FETCH_DATA_POSITION_FAILED: 'FETCH_DATA_POSITION_FAILED',

    FETCH_DATA_TIME_SUCCESS: 'FETCH_DATA_TIME_SUCCESS',
    FETCH_DATA_TIME_FAILED: 'FETCH_DATA_TIME_FAILED',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',

    GET_ALL_USER_SUCCESS: 'GET_ALL_USER_SUCCESS',
    GET_ALL_USER_FAILED: 'GET_ALL_USER_FAILED',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',

    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILED: 'UPDATE_USER_FAILED',

    GET_TOP_DOCTOR_SUCCESS: 'GET_TOP_DOCTOR_SUCCESS',
    GET_TOP_DOCTOR_FAILED: 'GET_TOP_DOCTOR_FAILED',

    GET_ALL_DOCTOR_SUCCESS: 'GET_ALL_DOCTOR_SUCCESS',
    GET_ALL_DOCTOR_FAILED: 'GET_ALL_DOCTOR_FAILED',

    SAVE_INFOR_DOCTOR_SUCCESS: 'SAVE_INFOR_DOCTOR_SUCCESS',
    SAVE_INFOR_DOCTOR_FAILED: 'SAVE_INFOR_DOCTOR_FAILED',

    GET_DETAIL_DOCTOR_SUCCESS: 'GET_DETAIL_DOCTOR_SUCCESS',
    GET_DETAIL_DOCTOR_FAILED: 'GET_DETAIL_DOCTOR_FAILED',

    CREATE_SCHEDULE_SUCCESS: 'CREATE_SCHEDULE_SUCCESS',
    CREATE_SCHEDULE_FAILED: 'CREATE_SCHEDULE_FAILED',

    GET_AVAILABLE_SCHEDULE_SUCCESS: 'GET_AVAILABLE_SCHEDULE_SUCCESS',
    GET_AVAILABLE_SCHEDULE_FAILED: 'GET_AVAILABLE_SCHEDULE_FAILED',

    FETCH_DATA_DOCTOR_INFOR_SELECT_SUCCESS: 'FETCH_DATA_DOCTOR_INFOR_SELECT_SUCCESS',
    FETCH_DATA_DOCTOR_INFOR_SELECT_FAILED: 'FETCH_DATA_DOCTOR_INFOR_SELECT_FAILED',

    FETCH_DATA_PROFILE_DOCTOR_SELECT_SUCCESS: 'FETCH_DATA_PROFILE_DOCTOR_SELECT_SUCCESS',
    FETCH_DATA_PROFILE_DOCTOR_SELECT_FAILED: 'FETCH_DATA_DOCTOR_INFOR_SELECT_FAILED',


})

export default actionTypes;